<?php

include_once('touchdown_core.features.inc');

/**
 * Implementation of hook_menu().
 */
function touchdown_core_menu() {
  $items = array();
  $items['home'] = array(
    'page callback' => 'touchdown_front_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Front page callback.
 */
function touchdown_front_page() {
  $context = context_load('touchdown');
  context_set('context', 'touchdown', $context);
  return '';
}
